# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "boa-ideas-home-assignment"
client_id = "4710ed07d164ab4c7b4ce8c819a849bf"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false

[build]
dev_store_url = "home-assignment-76.myshopify.com"
