# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "88b30806de29bd1395ddabbaf830de3a"
name = "boa-home-task-OB"
handle = "boa-home-task-ob-1"
application_url = "https://mouth-dispatch-stupid-cartoon.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "home-assignment-76.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://mouth-dispatch-stupid-cartoon.trycloudflare.com/auth/callback",
  "https://mouth-dispatch-stupid-cartoon.trycloudflare.com/auth/shopify/callback",
  "https://mouth-dispatch-stupid-cartoon.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[app_proxy]
url = "https://mouth-dispatch-stupid-cartoon.trycloudflare.com/cartsession"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = false
